IMAGE_WITHOUT_ALT = 15
IMAGE_WITHOUT_WIDTH = 5
IMAGE_WITHOUT_HEIGHT = 5
IMAGE_REMOTE = 2

HTTP_LINK = 15
MISSING_HREF = 20

MISSING_HEADINGS = 10
EMPTY_HEADING = 5
BUTTON_WITHOUT_TEXT = 10
TABLE_WITHOUT_HEADERS = 10

IMAGE_WEIGHT = 0.4
LINK_WEIGHT = 0.4
ACCESSIBILITY_WEIGHT = 0.2